# Generated by Django 3.2.25 on 2025-06-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景點名稱')),
                ('description', models.TextField(verbose_name='介紹')),
                ('image_url', models.URLField(verbose_name='圖片網址')),
                ('total_votes', models.IntegerField(default=0, verbose_name='總投票分數')),
                ('vote_count', models.IntegerField(default=0, verbose_name='投票人數')),
            ],
        ),
    ]
