# Generated by Django 3.2.25 on 2025-06-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(max_length=500, verbose_name='圖片網址'),
        ),
    ]
