# Generated by Django 3.2.25 on 2025-06-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_alter_place_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_url',
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='圖片'),
        ),
    ]
