# Generated by Django 3.2.25 on 2025-07-01 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=models.IntegerField(),
        ),
    ]
