# Generated by Django 3.2.25 on 2025-07-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0007_auto_20250701_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='圖片路徑'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.CharField(max_length=255, verbose_name='圖片路徑'),
        ),
    ]
